const settingTypes = {
  SET_CATEGORY: 'SET_CATEGORY',
  SET_GLASS: 'SET_GLASS',
  SET_INGREDIENTS: 'SET_INGREDIENTS',
  SET_ALCOHOLIC_FILTER: 'SET_ALCOHOLIC_FILTER',
  CLEAR_SETTINGS: 'CLEAR_SETTINGS',

  UNSET_CATEGORY: 'UNSET_CATEGORY',
  UNSET_GLASS: 'UNSET_GLASS',
  UNSET_INGREDIENTS: 'UNSET_INGREDIENTS',
  UNSET_ALCOHOLIC_FILTER: 'UNSET_ALCOHOLIC_FILTER',
};

export default settingTypes;
