const filtersTypes = {
  INGREDIENTS_FETCH_START: 'SIGN_OUT_USER_START',
  INGREDIENTS_FETCH_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  INGREDIENTS_ERROR: 'INGREDIENTS_ERROR',
};

export default filtersTypes;
