const filtersTypes = {
  INGREDIENTS_FETCH_START: 'SIGN_OUT_USER_START',
  INGREDIENTS_FETCH_SUCCESS: 'SIGN_OUT_USER_SUCCESS',

  CATEGORIES_FETCH_START: 'CATEGORIES_FETCH_START',
  CATEGORIES_FETCH_SUCCESS: 'CATEGORIES_FETCH_SUCCESS',

  GLASSES_FETCH_START: 'GLASSES_FETCH_START',
  GLASSES_FETCH_SUCCESS: 'GLASSES_FETCH_SUCCESS',

  ALCOHILIC_FILTERS_FETCH_START: 'ALCOHILIC_FILTERS_FETCH_START',
  ALCOHILIC_FILTERS_FETCH_SUCCESS: 'ALCOHILIC_FILTERS_FETCH_SUCCESS',

  INGREDIENTS_ERROR: 'INGREDIENTS_ERROR',
};

export default filtersTypes;
