const userTypes = {
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGNIN_IN_SUCCESS',
  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  RESET_USER_STATE: 'RESET_USER_STATE',
  USER_ERROR: 'USER_ERROR',
};

export default userTypes;
