const randomMock = {
  drinks: [
    {
      idDrink: '16942',
      strDrink: 'Zipperhead',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Whiskey sour glass',
      strInstructions:
        'Fill glass with rocks, add straw before putting in liquor. Then add the ingredients in order, trying to keep layered as much as possible (i.e. Chambord on bottom, then Vodka, Then soda on top).',
      strInstructionsES: null,
      strInstructionsDE:
        'Das Glas mit Eisw\u00fcrfeln f\u00fcllen, Trinkhalm hinzuf\u00fcgen und in den Schnaps geben. Dann f\u00fcgen Sie die Zutaten in der Reihenfolge hinzu und versuchen Sie, so viel wie m\u00f6glich geschichtet zu halten (z.B. Chambord unten, dann Wodka, dann Soda oben).',
      strInstructionsFR: null,
      strInstructionsIT:
        'Riempi il bicchiere con il ghiaccio, aggiungi la cannuccia prima di aggiungere il liquore.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/r2qzhu1485620235.jpg',
      strIngredient1: 'Chambord raspberry liqueur',
      strIngredient2: 'Vodka',
      strIngredient3: 'Soda water',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 shot ',
      strMeasure2: '1 shot ',
      strMeasure3: 'Fill with ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-01-28 16:17:15',
    },
    {
      idDrink: '12362',
      strDrink: 'Tequila Fizz',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins glass',
      strInstructions:
        'Shake all ingredients (except ginger ale) with ice and strain into a collins glass over ice cubes. Fill with ginger ale, stir, and serve.',
      strInstructionsES: null,
      strInstructionsDE:
        'Alle Zutaten (au\u00dfer Ginger Ale) mit Eis sch\u00fctteln und in ein Collins-Glas \u00fcber Eisw\u00fcrfel abseihen. Mit Ginger Ale f\u00fcllen, umr\u00fchren und servieren.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Shakerare tutti gli ingredienti (eccetto ginger ale) con ghiaccio e filtrare in un bicchiere Collins con cubetti di ghiaccio.Riempi con ginger ale, mescola e servi.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/2bcase1504889637.jpg',
      strIngredient1: 'Tequila',
      strIngredient2: 'Lemon juice',
      strIngredient3: 'Grenadine',
      strIngredient4: 'Egg white',
      strIngredient5: 'Ginger ale',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 tblsp ',
      strMeasure3: '3/4 oz ',
      strMeasure4: '1 ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-08 17:53:57',
    },
    {
      idDrink: '15006',
      strDrink: 'Turkeyball',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: 'Shake with ice and strain into a shot glass.',
      strInstructionsES: null,
      strInstructionsDE:
        'Mit Eis sch\u00fctteln und in ein Schnapsglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Shakerare con ghiaccio e filtra in un bicchiere da shot',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/rxurpr1441554292.jpg',
      strIngredient1: 'Wild Turkey',
      strIngredient2: 'Amaretto',
      strIngredient3: 'Pineapple juice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '3/4 oz ',
      strMeasure3: '1 splash ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2015-09-06 16:44:53',
    },
  ],
};

export default randomMock;
