const favsTypes = {
  POST_FAV_START: 'SAVE_FAV_START',
  GET_FAVS_START: 'GET_FAVS_START',
  SET_FAVS: 'SET_FAVS',
  SET_FAVS_ERROR: 'SET_FAVS_ERROR',
  DELETE_FAV_START: 'DELETE_FAV_START',
};

export default favsTypes;
